environment: canary-mumbai
cluster: ithacanoemon

serviceAccount:
  create: true
  annotations: {}
  name: ""

commonLabels:
  app.kubernetes.io/part-of: ithaca-interface-canary-mumbai
  app.kubernetes.io/component: ithaca-interface

deployment:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  image:
    repository: 178687878333.dkr.ecr.eu-west-1.amazonaws.com/ithacanoemon-interface
    pullPolicy: IfNotPresent
    tag: "main"

    args:
      - ""

  volumes:
    - name: environment-config
      configMap:
        name: ithaca-interface-canary-mumbai-config
  volumeMounts:
    - name: environment-config
      mountPath: /app/public/environment
      readOnly: true

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 512Mi

  envFrom:
    []
    # - type: configmap
    #   suffix: config
    # - type: secret
    #   suffix: secret

  livenessProbe: {}
  readinessProbe: {}

configMap:
  config:
    suffix: config
    data:
      environment.json: |
        {
            "API_URL": "https://mumbai.canary.ithacanoemon.tech/api/v1",
            "WS_URL": "wss://mumbai.canary.ithacanoemon.tech/wss",
            "POINTS_URL": "https://mumbai.canary.ithacanoemon.tech",
            "KYC_URL": "https://ithaca-ip-kyc-production.up.railway.app",
            "GRAFANA_URL": "https://dashboard.canary.ithacanoemon.tech/"
        }

service:
  enabled: true
  type: ClusterIP
  port: []

ingress: []

externalSecret:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
