apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: generic-helm-chart
    repo: https://aaronforce1.github.io/generic-helm-chart
    version: 0.3.9
    releaseName: ithaca-interface
    namespace: ithaca-uat
    valuesFile: "./values.yaml"
    valuesInline:
      nameOverride: ithaca-interface
      fullnameOverride: ithaca-interface
      service:
        port:
          - port: 3000
            targetPort: 3000
            protocol: TCP
            name: http
      deployment:
        service:
          port:
            - containerPort: 3000
              protocol: TCP
              name: http
      ingress:
        - enabled: false
          name: frontend-secondary
          className: nginx-secondary
          hosts:
            - host: testnet.ithacaprotocol.io
              http:
                paths:
                  - backend:
                      service:
                        name: ithaca-interface
                        port:
                          number: 3000
                    path: /
                    pathType: Prefix
          tls:
            - hosts:
                - testnet.ithacaprotocol.io
              secretName: testnet.ithacaprotocol.io-wildcard-tls-cert-secret
        - enabled: false
          name: frontend
          className: nginx
          hosts:
            - host: testnet.ithacaprotocol.io
              http:
                paths:
                  - backend:
                      service:
                        name: ithaca-interface
                        port:
                          number: 3000
                    path: /
                    pathType: Prefix
          tls:
            - hosts:
                - testnet.ithacaprotocol.io
              secretName: testnet.ithacaprotocol.io-wildcard-tls-cert-secret
