apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ithaca-canary-sepolia

helmCharts:
  - name: generic-helm-chart
    repo: https://aaronforce1.github.io/generic-helm-chart
    version: 0.3.9
    releaseName: ithaca-interface-canary-sepolia
    namespace: ithaca-canary-sepolia
    valuesFile: "./values.yaml"
    valuesInline:
      nameOverride: ithaca-interface-canary-sepolia
      fullnameOverride: ithaca-interface-canary-sepolia
      service:
        port:
          - port: 3000
            targetPort: 3000
            protocol: TCP
            name: http
      deployment:
        service:
          port:
            - containerPort: 3000
              protocol: TCP
              name: http
      ingress:
        - enabled: true
          name: frontend
          className: nginx
          hosts:
            - host: app.canary.ithacanoemon.tech
              http:
                paths:
                  - backend:
                      service:
                        name: ithaca-interface-canary-sepolia
                        port:
                          number: 3000
                    path: /
                    pathType: Prefix
          tls:
            - hosts:
                - app.canary.ithacanoemon.tech
              secretName: canary.ithacanoemon.tech-wildcard-tls-secret
