import { SIDE } from "@/utils/types";

export type PrepackagedStrategy = {
  label: string;
  key: string;
  strategies: StrategyLeg[];
};

export type StrategyLeg = {
  product: string;
  type: string;
  payoff: string;
  side: SIDE;
  size: number;
  strikeIndex: number;
  strike: string;
  linked: boolean;
  contractId: number;
  referencePrice: number;
};

export const STRUCTURED_STRATEGIES: PrepackagedStrategy[] = [
  {
    label: "Bet (Inside)",
    key: "bet-inside",
    strategies: [
      {
        product: "digital-option",
        type: "BinaryCall",
        payoff: "BinaryCall",
        side: SIDE.BUY,
        size: 100,
        strikeIndex: 0,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "digital-option",
        type: "BinaryCall",
        payoff: "BinaryCall",
        side: SIDE.SELL,
        size: 100,
        strikeIndex: 2,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Bet (Outside)",
    key: "bet-outside",
    strategies: [
      {
        product: "digital-option",
        type: "BinaryPut",
        payoff: "BinaryPut",
        side: SIDE.BUY,
        size: 100,
        strikeIndex: 0,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "digital-option",
        type: "BinaryCall",
        payoff: "BinaryCall",
        side: SIDE.BUY,
        size: 100,
        strikeIndex: 2,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Bonus",
    key: "bonus",
    strategies: [
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: -1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.SELL,
        size: 1,
        strikeIndex: -3,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "digital-option",
        type: "BinaryPut",
        payoff: "BinaryPut",
        side: SIDE.SELL,
        size: 200,
        strikeIndex: -3,
        strike: "",
        linked: false,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "Forward",
        type: "NEXT_AUCTION",
        payoff: "NEXT_AUCTION",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: -1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Twin-Win",
    key: "twin-win",
    strategies: [
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.BUY,
        size: 2,
        strikeIndex: -1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.SELL,
        size: 2,
        strikeIndex: -3,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "digital-option",
        type: "BinaryPut",
        payoff: "BinaryPut",
        side: SIDE.SELL,
        size: 400,
        strikeIndex: -3,
        strike: "",
        linked: false,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "Forward",
        type: "NEXT_AUCTION",
        payoff: "NEXT_AUCTION",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: -1,
        strike: "",
        linked: false,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Up n In Call",
    key: "up-n-in-call",
    strategies: [
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: 2,
        strike: "",
        linked: false,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "digital-option",
        type: "BinaryCall",
        payoff: "BinaryCall",
        side: SIDE.BUY,
        size: 200,
        strikeIndex: 2,
        strike: "",
        linked: false,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Up n Out Call",
    key: "up-n-out-call",
    strategies: [
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: 0,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.SELL,
        size: 1,
        strikeIndex: 2,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "digital-option",
        type: "BinaryCall",
        payoff: "BinaryCall",
        side: SIDE.SELL,
        size: 200,
        strikeIndex: 2,
        strike: "",
        linked: false,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Down n In Put",
    key: "down-in-put",
    strategies: [
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: -2,
        strike: "",
        linked: false,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "digital-option",
        type: "BinaryPut",
        payoff: "BinaryPut",
        side: SIDE.BUY,
        size: 200,
        strikeIndex: -2,
        strike: "",
        linked: false,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Down n Out Put",
    key: "down-out-put",
    strategies: [
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: 0,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.SELL,
        size: 1,
        strikeIndex: -2,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "digital-option",
        type: "BinaryPut",
        payoff: "BinaryPut",
        side: SIDE.SELL,
        size: 200,
        strikeIndex: -2,
        strike: "",
        linked: false,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
];

export const LINEAR_STRATEGIES = [
  {
    label: "Call Spread",
    key: "call-spread",
    strategies: [
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: 1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.SELL,
        size: 1,
        strikeIndex: 2,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Put Spread",
    key: "put-spread",
    strategies: [
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: 0,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.SELL,
        size: 1,
        strikeIndex: -1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Risk Reversal",
    key: "risk-reversal",
    strategies: [
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: 1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.SELL,
        size: 1,
        strikeIndex: -1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Call Ladder",
    key: "call-ladder",
    strategies: [
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: -1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.SELL,
        size: 1,
        strikeIndex: 0,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.SELL,
        size: 1,
        strikeIndex: 1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Put Ladder",
    key: "put-ladder",
    strategies: [
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: 1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.SELL,
        size: 1,
        strikeIndex: 0,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.SELL,
        size: 1,
        strikeIndex: -1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Straddle",
    key: "straddle",
    strategies: [
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: 0,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: 0,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Strangle",
    key: "strangle",
    strategies: [
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: 1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: -1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Call Condor",
    key: "call-condor",
    strategies: [
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: -2,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.SELL,
        size: 1,
        strikeIndex: -1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.SELL,
        size: 1,
        strikeIndex: 1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: 2,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Put Condor",
    key: "put-condor",
    strategies: [
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: -2,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.SELL,
        size: 1,
        strikeIndex: -1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.SELL,
        size: 1,
        strikeIndex: 1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: 2,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Iron Condor",
    key: "iron-condor",
    strategies: [
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: -2,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.SELL,
        size: 1,
        strikeIndex: -1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.SELL,
        size: 1,
        strikeIndex: 1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: 2,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Call Butterfly",
    key: "call-butterfly",
    strategies: [
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: -1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.SELL,
        size: 2,
        strikeIndex: 0,
        strike: "",
        linked: false,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Call",
        payoff: "Call",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: 1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
  {
    label: "Put Butterfly",
    key: "put-butterfly",
    strategies: [
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: -1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.SELL,
        size: 2,
        strikeIndex: 0,
        strike: "",
        linked: false,
        contractId: 0,
        referencePrice: 0,
      },
      {
        product: "option",
        type: "Put",
        payoff: "Put",
        side: SIDE.BUY,
        size: 1,
        strikeIndex: 1,
        strike: "",
        linked: true,
        contractId: 0,
        referencePrice: 0,
      },
    ],
  },
];
