export const mockedPositions = {
  result: "OK",
  details: "",
  payload: [
    {
      contractId: 1552,
      positionsAvgPrice: 67.831,
      positionsQty: 0.2,
      orders: [
        {
          revDate: 1721034840000,
          orderId: 1762338306455653,
          clientId: 1751386006009857,
          orderStatus: "FILLED",
          netPrice: 13.92,
          orderGenesis: "CLIENT_PREDEFINED",
          orderDescr: "Call",
          timeInForce: "GOOD_TILL_CANCEL",
          orderClass: "ConditionalOrder",
          requestSinglePrice: true,
          iocAuctionTime: 0,
          details: [
            {
              contractId: 1552,
              contractDto: {
                contractId: 1552,
                payoff: "Call",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3400.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "BUY",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 67.831,
              totalCost: 13.5662,
              execPrice: 67.831,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
          ],
          insertionDate: 1721034853955,
          execFeePaid: 0.276,
        },
      ],
    },
    {
      contractId: 1540,
      positionsAvgPrice: 0.0,
      positionsQty: 0.0,
      orders: [
        {
          revDate: 1721033580000,
          orderId: 1762338197679205,
          clientId: 1751386006009857,
          orderStatus: "FILLED",
          netPrice: 4.536,
          orderGenesis: "CLIENT_PREDEFINED",
          orderDescr: "Call Spread",
          timeInForce: "GOOD_TILL_CANCEL",
          orderClass: "ConditionalOrder",
          requestSinglePrice: true,
          iocAuctionTime: 0,
          details: [
            {
              contractId: 1532,
              contractDto: {
                contractId: 1532,
                payoff: "Call",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3600.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "SELL",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 18.4245,
              totalCost: 3.6849,
              execPrice: 18.4247,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
            {
              contractId: 1540,
              contractDto: {
                contractId: 1540,
                payoff: "Call",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3500.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "BUY",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 34.336,
              totalCost: 6.8672,
              execPrice: 34.3361,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
          ],
          insertionDate: 1721033596144,
          execFeePaid: 0.4416,
        },
        {
          revDate: 1721033580000,
          orderId: 1762338211350629,
          clientId: 1751386006009857,
          orderStatus: "FILLED",
          netPrice: -7.214,
          orderGenesis: "CLIENT_PREDEFINED",
          orderDescr: "Iron Condor",
          timeInForce: "GOOD_TILL_CANCEL",
          orderClass: "ConditionalOrder",
          requestSinglePrice: true,
          iocAuctionTime: 0,
          details: [
            {
              contractId: 1532,
              contractDto: {
                contractId: 1532,
                payoff: "Call",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3600.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "BUY",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 18.4245,
              totalCost: 3.6849,
              execPrice: 18.4247,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
            {
              contractId: 1540,
              contractDto: {
                contractId: 1540,
                payoff: "Call",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3500.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "SELL",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 34.336,
              totalCost: 6.8672,
              execPrice: 34.3361,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
            {
              contractId: 1562,
              contractDto: {
                contractId: 1562,
                payoff: "Put",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3300.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "SELL",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 54.7155,
              totalCost: 10.9431,
              execPrice: 54.7156,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
            {
              contractId: 1566,
              contractDto: {
                contractId: 1566,
                payoff: "Put",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3200.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "BUY",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 30.241,
              totalCost: 6.0482,
              execPrice: 30.241,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
          ],
          insertionDate: 1721033596144,
          execFeePaid: 0.7728,
        },
      ],
    },
    {
      contractId: 1562,
      positionsAvgPrice: 54.7155,
      positionsQty: -0.2,
      orders: [
        {
          revDate: 1721033580000,
          orderId: 1762338211350629,
          clientId: 1751386006009857,
          orderStatus: "FILLED",
          netPrice: -7.214,
          orderGenesis: "CLIENT_PREDEFINED",
          orderDescr: "Iron Condor",
          timeInForce: "GOOD_TILL_CANCEL",
          orderClass: "ConditionalOrder",
          requestSinglePrice: true,
          iocAuctionTime: 0,
          details: [
            {
              contractId: 1532,
              contractDto: {
                contractId: 1532,
                payoff: "Call",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3600.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "BUY",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 18.4245,
              totalCost: 3.6849,
              execPrice: 18.4247,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
            {
              contractId: 1540,
              contractDto: {
                contractId: 1540,
                payoff: "Call",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3500.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "SELL",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 34.336,
              totalCost: 6.8672,
              execPrice: 34.3361,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
            {
              contractId: 1562,
              contractDto: {
                contractId: 1562,
                payoff: "Put",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3300.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "SELL",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 54.7155,
              totalCost: 10.9431,
              execPrice: 54.7156,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
            {
              contractId: 1566,
              contractDto: {
                contractId: 1566,
                payoff: "Put",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3200.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "BUY",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 30.241,
              totalCost: 6.0482,
              execPrice: 30.241,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
          ],
          insertionDate: 1721033596144,
          execFeePaid: 0.7728,
        },
      ],
    },
    {
      contractId: 1532,
      positionsAvgPrice: 0.0,
      positionsQty: 0.0,
      orders: [
        {
          revDate: 1721033580000,
          orderId: 1762338197679205,
          clientId: 1751386006009857,
          orderStatus: "FILLED",
          netPrice: 4.536,
          orderGenesis: "CLIENT_PREDEFINED",
          orderDescr: "Call Spread",
          timeInForce: "GOOD_TILL_CANCEL",
          orderClass: "ConditionalOrder",
          requestSinglePrice: true,
          iocAuctionTime: 0,
          details: [
            {
              contractId: 1532,
              contractDto: {
                contractId: 1532,
                payoff: "Call",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3600.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "SELL",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 18.4245,
              totalCost: 3.6849,
              execPrice: 18.4247,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
            {
              contractId: 1540,
              contractDto: {
                contractId: 1540,
                payoff: "Call",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3500.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "BUY",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 34.336,
              totalCost: 6.8672,
              execPrice: 34.3361,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
          ],
          insertionDate: 1721033596144,
          execFeePaid: 0.4416,
        },
        {
          revDate: 1721033580000,
          orderId: 1762338211350629,
          clientId: 1751386006009857,
          orderStatus: "FILLED",
          netPrice: -7.214,
          orderGenesis: "CLIENT_PREDEFINED",
          orderDescr: "Iron Condor",
          timeInForce: "GOOD_TILL_CANCEL",
          orderClass: "ConditionalOrder",
          requestSinglePrice: true,
          iocAuctionTime: 0,
          details: [
            {
              contractId: 1532,
              contractDto: {
                contractId: 1532,
                payoff: "Call",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3600.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "BUY",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 18.4245,
              totalCost: 3.6849,
              execPrice: 18.4247,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
            {
              contractId: 1540,
              contractDto: {
                contractId: 1540,
                payoff: "Call",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3500.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "SELL",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 34.336,
              totalCost: 6.8672,
              execPrice: 34.3361,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
            {
              contractId: 1562,
              contractDto: {
                contractId: 1562,
                payoff: "Put",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3300.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "SELL",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 54.7155,
              totalCost: 10.9431,
              execPrice: 54.7156,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
            {
              contractId: 1566,
              contractDto: {
                contractId: 1566,
                payoff: "Put",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3200.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "BUY",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 30.241,
              totalCost: 6.0482,
              execPrice: 30.241,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
          ],
          insertionDate: 1721033596144,
          execFeePaid: 0.7728,
        },
      ],
    },
    {
      contractId: 1566,
      positionsAvgPrice: 30.241,
      positionsQty: 0.2,
      orders: [
        {
          revDate: 1721033580000,
          orderId: 1762338211350629,
          clientId: 1751386006009857,
          orderStatus: "FILLED",
          netPrice: -7.214,
          orderGenesis: "CLIENT_PREDEFINED",
          orderDescr: "Iron Condor",
          timeInForce: "GOOD_TILL_CANCEL",
          orderClass: "ConditionalOrder",
          requestSinglePrice: true,
          iocAuctionTime: 0,
          details: [
            {
              contractId: 1532,
              contractDto: {
                contractId: 1532,
                payoff: "Call",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3600.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "BUY",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 18.4245,
              totalCost: 3.6849,
              execPrice: 18.4247,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
            {
              contractId: 1540,
              contractDto: {
                contractId: 1540,
                payoff: "Call",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3500.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "SELL",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 34.336,
              totalCost: 6.8672,
              execPrice: 34.3361,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
            {
              contractId: 1562,
              contractDto: {
                contractId: 1562,
                payoff: "Put",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3300.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "SELL",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 54.7155,
              totalCost: 10.9431,
              execPrice: 54.7156,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
            {
              contractId: 1566,
              contractDto: {
                contractId: 1566,
                payoff: "Put",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  strike: 3200.0,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "BUY",
              originalQty: 0.2,
              remainingQty: 0.0,
              thisFillQty: 0.2,
              cancelledQty: 0.0,
              avgPrice: 30.241,
              totalCost: 6.0482,
              execPrice: 30.241,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
          ],
          insertionDate: 1721033596144,
          execFeePaid: 0.7728,
        },
      ],
    },
    {
      contractId: 1600,
      positionsAvgPrice: 3346.12,
      positionsQty: 0.015,
      orders: [
        {
          revDate: 1721045760000,
          orderId: 1762350803775589,
          clientId: 1751386006009857,
          orderStatus: "FILLED",
          netPrice: 50.2154,
          orderGenesis: "CLIENT_PREDEFINED",
          orderDescr: "Forward",
          timeInForce: "GOOD_TILL_CANCEL",
          orderClass: "ConditionalOrder",
          requestSinglePrice: true,
          iocAuctionTime: 0,
          details: [
            {
              contractId: 1600,
              contractDto: {
                contractId: 1600,
                payoff: "Forward",
                economics: {
                  currencyPair: "WETH/USDC",
                  expiry: 240719080,
                  priceCurrency: "USDC",
                  qtyCurrency: "WETH",
                },
                tradeable: true,
              },
              side: "BUY",
              originalQty: 0.015,
              remainingQty: 0.0,
              thisFillQty: 0.015,
              cancelledQty: 0.0,
              avgPrice: 3346.12,
              totalCost: 50.1918,
              execPrice: 3346.125,
              currencyPair: "WETH/USDC",
              expiry: 240719080,
            },
          ],
          insertionDate: 1721045782923,
          execFeePaid: 0.01,
        },
      ],
    },
  ],
};
