environment: uat
cluster: ithacanoemon

serviceAccount:
  create: true
  annotations: {}
  name: ""

commonLabels:
  app.kubernetes.io/part-of: ithaca-interface
  app.kubernetes.io/component: ithaca-interface

deployment:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  imagePullSecrets: []
  image:
    repository: 697578532656.dkr.ecr.eu-west-1.amazonaws.com/ithacanoemon-interface
    pullPolicy: IfNotPresent
    tag: "v1.17.0"

    args:
      - ""

  volumes:
    - name: environment-config
      configMap:
        name: ithaca-interface-config
  volumeMounts:
    - name: environment-config
      mountPath: /app/public/environment
      readOnly: true

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

  resources:
    requests:
      cpu: 8
      memory: 8192Mi
    limits:
      cpu: 8
      memory: 8192Mi

  envFrom:
    []
    # - type: configmap
    #   suffix: config
    # - type: secret
    #   suffix: secret

  livenessProbe: {}
  readinessProbe: {}

configMap:
  config:
    suffix: config
    data:
      environment.json: |
        {
            "API_URL": "https://app.ithacaprotocol.io/api/v1",
            "WS_URL": "wss://app.ithacaprotocol.io/wss",
            "POINTS_URL": "https://app.ithacaprotocol.io/api/points/v3",
            "KYC_URL": "https://app.ithacaprotocol.io",
            "GRAFANA_URL": "dashboard.ithacanoemon.tech",
            "TRADING_URL": "https://app.ithacaprotocol.io",
            "DISABLE_POINTS_REDEMPTION": "true",
            "SUBGRAPH_URL": "https://api.studio.thegraph.com/query/43740/ithaca-arbitrum/v1.1.0",
            "SQUID_API_URL": "https://api.squidrouter.com/"
        }

service:
  enabled: true
  type: ClusterIP
  port: []

ingress: []

externalSecret:
  enabled: false

autoscaling:
  enabled: true
  minReplicas: 7
  maxReplicas: 15
